apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: keycloak
spec:
  ports:
   - port: 3306
  selector:
    app: mysql
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: keycloak
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.21
          env: 
            - name: MYSQL_DATABASE
              value: keycloak
            - name: MYSQL_USER
              value: keycloak
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
          ports: 
            - containerPort: 3306